---
# tasks file for influxdb
- name: Install required dependencies
  apt:
    name:
      - apt-transport-https
      - software-properties-common
    state: present
    
- name: Import InfluxDB GPG key
  apt_key:
    url: https://repos.influxdata.com/influxdata-archive_compat.key
    state: present
    
- name: Add InfluxDB repository
  apt_repository:
    repo: 'deb https://repos.influxdata.com/debian stable main'
    state: present
    
- name: Install InfluxDB
  apt:
    name: influxdb
    state: present
    update_cache: true
    
- name: Configure InfluxDB
  template:
    src: influxdb.conf.j2
    dest: /etc/influxdb/influxdb.conf
    owner: influxdb
    group: influxdb
    mode: 0644
  notify: Restart InfluxDB
  
- name: Enable and start InfluxDB service
  service:
    name: influxdb
    enabled: true
    state: started
