---
# tasks file for grafana
- name: Install required dependencies
  apt:
     name:
        - apt-transport-https
        - software-properties-common
     state: present
     
- name: Import Grafana GPG key
  apt_key:
    url: https://packages.grafana.com/gpg.key
    state: present

- name: Add Grafana repository
  apt_repository:
    repo: 'deb https://packages.grafana.com/oss/deb stable main'
    state: present
    
- name: Install Grafana
  apt:
    name: grafana
    state: present
    update_cache: true
    
- name: Configure Grafana
  template:
    src: grafana.ini.j2
    dest: /etc/grafana/grafana.ini
    owner: grafana
    group: grafana
    mode: 0644
  notify: Restart Grafana
  
- name: Enable and start Grafana service
  systemd:
    name: grafana-server
    enabled: true
    state: started
