---
server.port: {{ server_port }}

server.host: "{{ server_host }}"

server.name: "{{ server_name }}"

elasticsearch.hosts: ["{{ elasticsearch_host }}"]

elasticsearch.username: "{{ kibana_username }}"
elasticsearch.password: "{{ kibana_password }}"
